name: CMake Multiplatform

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # Install dependencies for Linux
    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev libx11-dev libgl1-mesa-dev libxrandr-dev libxi-dev libudev-dev build-essential

    # Install dependencies for macOS
    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install sfml

    # Install vcpkg and dependencies for Windows
    - name: Install vcpkg on Windows
      if: runner.os == 'Windows'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe install sfml:x64-windows
        choco install ninja

    # Install vcpkg for Linux and macOS
    - name: Install vcpkg on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sfml

    # Set the environment variable for vcpkg
    - name: Set vcpkg environment
      run: echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_ENV

    # Configure CMake to use vcpkg toolchain
    - name: Configure CMake
      run: cmake . -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    # Build the project
    - name: Build
      run: cmake --build build

    # Run tests (if applicable)
    - name: Run Tests
      run: cd build && ctest
